apiVersion: v1
kind: Service
metadata:
  name: easy-rent-dev-redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: easy-rent-dev-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: easy-rent-dev-redis
spec:
  selector:
    matchLabels:
      app: easy-rent-dev-redis  # has to match .spec.template.metadata.labels
  serviceName: easy-rent-dev-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: easy-rent-dev-redis  # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: easy-rent-dev-redis
          image: redis:3.2-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "$(REDIS_PASS)", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: env-secrets-dev
                key: REDIS_PASS
          volumeMounts:
            - name: easy-rent-dev-volume
              mountPath: /data
      volumes:
        - name: easy-rent-dev-volume
          gcePersistentDisk:
            pdName: easy-rent-dev-redis
            fsType: ext4
