apiVersion: v1
kind: Service
metadata:
  name: dev-redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: dev-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-redis
spec:
  selector:
    matchLabels:
      app: dev-redis  # has to match .spec.template.metadata.labels
  serviceName: dev-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-redis  # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: dev-redis
          image: redis:3.2-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "$(REDIS_PASS)", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: env-secrets-dev
                key: REDIS_PASS
          volumeMounts:
            - name: dev-volume
              mountPath: /data
      volumes:
        - name: dev-volume
          gcePersistentDisk:
            pdName: dev-redis
            fsType: ext4
spec:
      containers:
        - name: tecca-stedi
          image: gcr.io/cubs-consulting/stedi
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-dev
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-dev"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER