steps:
#this step builds the container image.
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stedi-teca-dev:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: initalise intagration tests
    args:
      - build
      - -t
      - teca-stedi-tests
      - ./integration-tests
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stedi-teca-dev:latest"
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: Deploy
    args:
    - run
    - --filename=manifest.yaml
    - --image=gcr.io/$PROJECT_ID/stedi-teca-dev:latest
    - --location=us-east1-c
    - --output=/tmp/outputdev
    - --cluster=cluster-2
  - name: "gcr.io/cloud-builders/docker"
    id: run the intigration tests
    args:
      - run
      - teca-stedi-tests 
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy to Production
    args:
      - 'beta'
      - 'builds'
      - 'triggers'
      - 'run'
      - '2b1c6bb1-5cef-467e-b889-4a0f618e4299'
      - '--branch=main'
---
