steps:
  - name: gcr.io/cloud-builders/gke-deploy
    id: Deploy
    args:
      - run
      - --filename=prod-manifest.yaml
      - --image=gcr.io/$PROJECT_ID/stedi-teca-prod:latest
      - --location=us-east1-c
      - --cluster=cluster-2