  - name: "gcr.io/cloud-builders/gke-deploy"
    id: Deploy
    args:
    - run
    - --filename=manifest.yaml
    - --image=gcr.io/$PROJECT_ID/stedi-teca:latest
    - --location=us-east1-c
    - --output=/tmp/outputdev
    - --cluster=cluster-2
  